const fs = require("fs");
const path = require("path");

// Get the theme name from the environment variable, default to "default"
const theme = (process.env.PWP__THEME || "default").toLowerCase();

const themesDir = path.resolve(__dirname, "./app/assets/stylesheets/themes");
const shimPath = path.join(themesDir, "_selected.scss");
const themeFilePath = path.join(themesDir, `${theme}.css`);

if (!fs.existsSync(themeFilePath)) {
  console.error(`Error: Theme "${theme}" not found at ${themeFilePath}`);
  process.exit(1);
}

const contents = `// Auto-generated by set_theme.js — do not edit manually.
@use "themes/${theme}";
`;

fs.writeFileSync(shimPath, contents, "utf8");
console.log(`Theme shim written: ${shimPath} (@use themes/${theme})`);
