version: '2.1'

services:
  postgres:
    image: docker.io/postgres:15
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: passwordpusher_user
      POSTGRES_PASSWORD: passwordpusher_passwd
      POSTGRES_DB: passwordpusher_db

  passwordpusher:
    image: docker.io/pglombardo/pwpush:latest
    environment:
      DATABASE_URL: 'postgres://passwordpusher_user:passwordpusher_passwd@postgres:5432/passwordpusher_db'
    ports:
      - "5100:5100"
    depends_on:
      - postgres
    links:
     - postgres:postgres
    #
    # You can set environment variables here, or in a .env file.  See:
    # https://docs.docker.com/compose/environment-variables/
    #
    # Password Pusher provides an example Docker environment file:
    # https://github.com/pglombardo/PasswordPusher/tree/master/containers/docker/pwpush-docker-env-file
    #
    # See also the Password Pusher Configuration documentation
    # https://docs.pwpush.com/docs/config-strategies/
    #
    # Uncomment the following lines to set environment variables and add your own.
    # environment:
    #   PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT: "1"
    #   PWP__PW__EXPIRE_AFTER_VIEWS_MIN: "1"
    #   PWP__PW__RETRIEVAL_STEP_DEFAULT: "true"
    #
    # Uncomment the following lines to mount a volume.
    # volumes:
    #   # Example of a persistent volume for the storage directory (file uploads)
    #   - /path/to/directory:/opt/PasswordPusher/storage:rw
    #
    # Or you could override a single file in the container with a bind mount:
    # volumes:
    #   - type: bind
    #     source: /path/to/my/custom/settings.yml
    #     target: /opt/PasswordPusher/config/settings.yml
    #
    # To customise the application via configuration file, see settings.yml:
    # https://github.com/pglombardo/PasswordPusher/blob/master/config/settings.yml
    #
    # Then you can use the above bind mount to overlay the file into the container on boot.
