name: Post commit info to Campfire

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  post-commit-info:
    runs-on: ubuntu-latest
    steps:
      - name: Post commit info to Campfire
        if: secrets.CAMPFIRE_MESSAGES_URL != ''
        continue-on-error: true
        uses: shane-lamb/campfire-notify-action@df63cf73810147306276e281bedccf71c1519caf # v1.1.6
        with:
          messages_url: ${{ secrets.CAMPFIRE_MESSAGES_URL }}
          template: commit_pushed
